import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/kit/db";
import { requirePagePermission } from "@/kit/auth";
import { can } from "@/kit/rbac";
import { approvePreview, dispatchToDevin, updateChangeRequest } from "@/kit/requests-actions";
import { buildDevinPrompt, CLASSIFICATIONS, REQUEST_STATUSES, type Classification } from "@/kit/requests";
import { Badge, Card, Field, PageHeader, btn, fmtDate, input, label } from "@/kit/ui";
import { ActionForm } from "@/kit/ui/ActionForm";
import { AuditTimeline } from "@/kit/ui/AuditTimeline";
import { APPS } from "@/apps/manifest";

export default async function RequestPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requirePagePermission("requests.create");
  const { id } = await params;
  const r = await db.changeRequest.findUnique({ where: { id } });
  if (!r) notFound();
  const manage = can(user, "requests.manage");
  if (!manage && r.requesterId !== user.id) notFound();
  const cls = CLASSIFICATIONS[r.classification as Classification];
  const status = REQUEST_STATUSES[r.status];
  const closed = ["deployed", "declined"].includes(r.status);
  return (
    <>
      <Link href="/requests" className="text-sm text-indigo-600">← Change requests</Link>
      <PageHeader title={<span className="flex items-center gap-2">{r.title} <Badge tone={status?.tone}>{status?.label ?? r.status}</Badge></span>} subtitle={`${r.requesterName} · ${fmtDate(r.createdAt)} · ${APPS.find((a) => a.id === r.appId)?.name ?? r.appId}`} />
      <div className="grid gap-4 lg:grid-cols-3">
        <div className="space-y-4 lg:col-span-2">
          <Card title="Request">
            <p className="whitespace-pre-wrap text-sm text-slate-800">{r.description}</p>
            <dl className="mt-4 grid grid-cols-3 gap-4">
              <Field label="Touches">{cls?.label ?? r.classification}</Field>
              <Field label="Required reviewers">{cls?.reviewers.join(", ")}</Field>
              <Field label="Urgency">{r.urgency}</Field>
            </dl>
            {cls && <p className="mt-2 text-xs text-slate-500">{cls.note}</p>}
          </Card>
          {(r.prUrl || r.previewUrl) && (
            <Card title="Links">
              <dl className="grid grid-cols-2 gap-4">
                <Field label="Pull request">{r.prUrl ? <a className="text-indigo-700 underline" href={r.prUrl}>{r.prUrl}</a> : "—"}</Field>
                <Field label="Preview">{r.previewUrl ? <a className="text-indigo-700 underline" href={r.previewUrl}>{r.previewUrl}</a> : "—"}</Field>
              </dl>
            </Card>
          )}
          <Card title={r.prompt ? "Prompt sent to Devin" : "Prompt Devin would receive"}>
            <pre className="max-h-96 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-xs text-slate-700">{r.prompt ?? buildDevinPrompt(r)}</pre>
            <p className="mt-2 text-xs text-slate-500">Generated by <code>src/kit/requests.ts</code>: the ask plus the repo conventions and guardrails. No customer data, no credentials. The real dispatch is a POST to the Devin API from CI (docs/devin/automation.md); here the connector is a mock.</p>
          </Card>
        </div>
        <div className="space-y-4">
          {manage && r.status === "open" && (
            <Card title="Dispatch">
              <ActionForm action={dispatchToDevin} className="space-y-2">
                <input type="hidden" name="id" value={r.id} />
                <button className={btn.primary}>Send to Devin</button>
              </ActionForm>
              <ActionForm action={updateChangeRequest} className="mt-3 space-y-2">
                <input type="hidden" name="id" value={r.id} />
                <input type="hidden" name="status" value="declined" />
                <input name="reason" placeholder="Why decline?" className={input} />
                <button className={btn.danger}>Decline</button>
              </ActionForm>
            </Card>
          )}
          {manage && !closed && r.status !== "open" && (
            <Card title="Update progress">
              <ActionForm action={updateChangeRequest} className="space-y-2">
                <input type="hidden" name="id" value={r.id} />
                <div><label className={label} htmlFor="status">Status</label>
                  <select id="status" name="status" className={input} defaultValue={r.status === "dispatched" ? "pr_open" : r.status === "pr_open" ? "preview_ready" : "deployed"}>
                    <option value="pr_open">PR open</option><option value="preview_ready">Preview ready</option><option value="deployed">Deployed</option><option value="declined">Declined</option>
                  </select></div>
                <div><label className={label} htmlFor="prUrl">PR URL</label><input id="prUrl" name="prUrl" className={input} defaultValue={r.prUrl ?? ""} placeholder="https://github.com/…/pull/…" /></div>
                <div><label className={label} htmlFor="previewUrl">Preview URL</label><input id="previewUrl" name="previewUrl" className={input} defaultValue={r.previewUrl ?? ""} placeholder="https://…preview…" /></div>
                <input name="reason" placeholder="Note (required if declining)" className={input} />
                <button className={btn.secondary}>Save</button>
              </ActionForm>
            </Card>
          )}
          {r.status === "preview_ready" && r.requesterId === user.id && (
            <Card title="Confirm the preview">
              <p className="text-sm">Open the preview and check it does what you asked. Confirming lets engineering merge.</p>
              <ActionForm action={approvePreview} className="mt-2 space-y-2">
                <input type="hidden" name="id" value={r.id} />
                <input name="reason" placeholder="Optional note" className={input} />
                <button className={btn.primary}>It does what I asked</button>
              </ActionForm>
            </Card>
          )}
          <Card title="Audit trail"><AuditTimeline entityType="ChangeRequest" entityId={r.id} /></Card>
        </div>
      </div>
    </>
  );
}
